version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: $APP_STACKS_STATUS_IP
      APP_PORT: 3000
      #PROXY_AUTH_ADD: "false"
      PROXY_AUTH_WHITELIST: "/stacks-blockchain-api/*"


  stacks-status:
    image: ceramicwhite/stacks-status:latest@sha256:c32b2203269828e6ed06cbda5d190a4f2154d2923236cb02f3fcaeff2417cf32
    user: 1000:1000
    init: true
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - STACKS_API_HOST=http://$APP_STACKS_API_IP:$APP_STACKS_API_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_STATUS_IP
    depends_on:
      - stacks-blockchain-api

  stacks-blockchain:
    image: ceramicwhite/stacks-blockchain:2.1.0.0.0-bullseye-slim
    init: true
    restart: on-failure
    stop_grace_period: 15m
    #user: 1000:1000
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    command: 
      [
        "/usr/local/bin/stacks-node",
        "start",
        "--config",
        "/app/config/Config.toml",
      ]
    ports:
      - $APP_STACKS_CORE_RPC_PORT:$APP_STACKS_CORE_RPC_PORT
      - $APP_STACKS_CORE_P2P_PORT:$APP_STACKS_CORE_P2P_PORT
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config:ro
      - ${APP_DATA_DIR}/data/stacks-blockchain:/app/stacks-blockchain/data
    networks:
      default:
        ipv4_address: $APP_STACKS_BLOCKCHAIN_IP
    depends_on:
      - stacks-blockchain-api

  stacks-blockchain-api:
    image: ceramicwhite/stacks-blockchain-api:v7.1.1
    init: true
    restart: on-failure
    user: 0:0
    stop_grace_period: 15m
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    #command: ["npm", "run", "start"]
    command: ["/bin/sh", "-c", "/app/scripts/bns.sh && npm run start"]
    volumes:
      - ${APP_DATA_DIR}/data/bns-data:/app/bns-data
      - ${APP_DATA_DIR}/data/event-replay:/app/event-replay
    ports:
      - $APP_STACKS_CORE_EVENT_PORT:$APP_STACKS_CORE_EVENT_PORT
      - $APP_STACKS_API_PORT:$APP_STACKS_API_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_API_IP
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine@sha256:1f86ede0903f60ecd2eb630b15803567324da7aa0d1f7bbc3a8f1fe5247a4592
    init: true
    restart: on-failure
    stop_grace_period: 15m
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
    env_file:
      - ${APP_DATA_DIR}/data/config/setup.env
    ports:
      - $APP_STACKS_DB_PORT:$APP_STACKS_DB_PORT
    networks:
      default:
        ipv4_address: $APP_STACKS_DB_IP
